format_version = 1
file_descriptor = "Packages to include in the nightly sync to Acceptance Builder"

[[x86_64-linux]]
channel = "refresh-2020q1-006b"
packages = [
  "core/acl",
  "core/attr",
  "core/autoconf",
  "core/automake",
  "core/aws-cli",
  "core/bash",
  "core/bats",
  "core/bc",
  "core/binutils",
  "core/bison",
  "core/busybox-static",
  "core/bzip2",
  "core/bzip2-musl",
  "core/cacerts",
  "core/check",
  "core/clens",
  "core/cmake",
  "core/coreutils",
  "core/curl",
  "core/cyrus-sasl",
  "core/db",
  "core/dejagnu",
  "core/diffutils",
  "core/docker",
  "core/expat",
  "core/expect",
  "core/file",
  "core/findutils",
  "core/flex",
  "core/fontconfig",
  "core/freetype",
  "core/gawk",
  "core/gcc",
  "core/gcc-libs",
  "core/gdal",
  "core/gdbm",
  "core/geos",
  "core/gettext",
  "core/git",
  "core/glibc",
  "core/gmp",
  "core/grep",
  "core/groff",
  "core/gzip",
  "core/iana-etc",
  "core/inetutils",
  "core/less",
  "core/libarchive",
  "core/libarchive-musl",
  "core/libbsd",
  "core/libcap",
  "core/libedit",
  "core/libevent",
  "core/libffi",
  "core/libiconv",
  "core/libidn2",
  "core/libmpc",
  "core/libossp-uuid",
  "core/libpng",
  "core/libsodium",
  "core/libsodium-musl",
  "core/libtool",
  "core/libunistring",
  "core/libxml2",
  "core/linux-headers",
  "core/linux-headers-musl",
  "core/m4",
  "core/make",
  "core/memcached",
  "core/mg",
  "core/minio",
  "core/mpfr",
  "core/musl",
  "core/ncurses",
  "core/nghttp2",
  "core/nginx",
  "core/node",
  "core/openssh",
  "core/openssl",
  "core/openssl-fips",
  "core/openssl-musl",
  "core/patch",
  "core/patchelf",
  "core/pcre",
  "core/perl",
  "core/phantomjs",
  "core/pkg-config",
  "core/postgresql",
  "core/procps-ng",
  "core/proj",
  "core/protobuf",
  "core/protobuf-cpp",
  "core/protobuf-rust",
  "core/psmisc",
  "core/python2",
  "core/python",
  "core/python-minimal",
  "core/raml2html",
  "core/readline",
  "core/rq",
  "core/rust",
  "core/sed",
  "core/shadow",
  "core/sqlite",
  "core/tar",
  "core/tcl",
  "core/texinfo",
  "core/unzip",
  "core/util-linux",
  "core/vim",
  "core/wget",
  "core/xz",
  "core/xz-musl",
  "core/zeromq",
  "core/zlib",
  "core/zlib-musl"
]
